[project]
name = "my-notebook"
version = "0.1.0"
description = "Notebook project with custom deps"
authors = [
    { name = "Author", email = "author@example.com" }
]
dependencies = ["ipykernel~=6.23.1", "numpy~=1.24.3"]
readme = "README.md"
requires-python = ">= 3.10"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
[tool.hatch.metadata]
allow-direct-references = true
