[project]
name = "my-jupyterlab"
version = "0.3.0"
description = "Jupyterlab install"
authors = [
    { name = "Author", email = "author@example.com" }
]
readme = "README.md"
requires-python = ">= 3.11"
classifiers = [
    "Private :: Do Not Upload",
]

dependencies = [
    "jupyterlab",
    "pyproject-local-kernel @ git+https://github.com/bluss/pyproject-local-kernel",
    "jupytext>=1.16.1",
]

[tool.rye]
managed = true
virtual = true

[tool.hatch.metadata]
allow-direct-references = true
