name: Build and Publish

on:
  workflow_dispatch:
    inputs:
      publish_to_pypi:
        description: Actually publish
        type: boolean
        required: true

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Uv
      uses: astral-sh/setup-uv@v3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Build
      run: |
        git clean -fdx
        uv build -v
    - uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/
        retention-days: 14

  test-wheel:
    runs-on: ubuntu-latest
    needs: build-release
    steps:
    - uses: actions/checkout@v4
    - name: Install Uv
      uses: astral-sh/setup-uv@v3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/download-artifact@v4
      with:
        name: dist
        path: dist/
    - name: Tests
      run: |
        ./nox -s build-test

  upload-release:
    runs-on: ubuntu-latest
    needs: test-wheel
    environment:
      name: release
      url: https://pypi.org/project/pyproject-local-kernel/
    permissions:
      id-token: write
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: dist
        path: dist/
    - name: ls
      run: |
        ls -al -R
    - name: Check tag
      if:  ${{ ! startsWith(github.ref, 'refs/tags') }}
      run: exit 1
    - name: Check input yes/no
      if:  ${{ ! inputs.publish_to_pypi }}
      run: exit 1
    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        print-hash: true
        verbose: true
