name: Build and Publish

on:
  workflow_dispatch:
    inputs:
      publish_to_pypi:
        description: Actually publish
        type: boolean
        required: true

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Rye
      run: |
        curl -sSf https://rye.astral.sh/get | RYE_TOOLCHAIN_VERSION=$(cat .python-version) RYE_INSTALL_OPTION="--yes" bash
        echo "$HOME/.rye/shims" >> $GITHUB_PATH
    - name: Install Uv
      run: |
        rye tools install -f uv
    - name: Tests
      run: |
        make test
    - name: Build
      run: |
        git clean -fdx
        make build
    - uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/
        retention-days: 14

  upload-release:
    runs-on: ubuntu-latest
    needs: build-release
    environment:
      name: release
      url: https://pypi.org/project/pyproject-local-kernel/
    permissions:
      id-token: write
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: dist
        path: dist/
    - name: ls
      run: |
        ls -al -R
    - name: Check tag
      if:  ${{ ! startsWith(github.ref, 'refs/tags') }}
      run: exit 1
    - name: Check input yes/no
      if:  ${{ ! inputs.publish_to_pypi }}
      run: exit 1
    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        print-hash: true
        verbose: true
