name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests-linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v4
    - name: Install Rye
      run: |
        env curl -sSf https://rye-up.com/get | RYE_TOOLCHAIN_VERSION=$(cat .python-version) RYE_INSTALL_OPTION="--yes" bash
        source ~/.rye/env
        rye config --set-bool behavior.use-uv=true
    - name: Rye Sync
      run: |
        source ~/.rye/env
        rye sync
    - name: Tests
      run: |
        source ~/.rye/env
        rye test -v
    - name: Execute notebook
      run: |
        source ~/.rye/env
        ./tests/server-client/setup_run.sh

  tests-windows:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
    name: tests-windows/${{ matrix.rust }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - name: Install Rye
        shell: bash
        run: |
          cargo install --debug rye --git https://github.com/astral-sh/rye
          rye self install --toolchain-version $(cat .python-version) --modify-path -y
          rye config --set-bool behavior.use-uv=true
      - name: Rye Sync
        shell: bash
        run: |
          rye sync
      - name: Tests
        shell: bash
        run: |
          rye test -v
      - name: Execute notebook
        run: |
          source ~/.rye/env
          ./tests/server-client/setup_run.sh
