name: CI

on:
  push:
    paths:
      - '**'
      - '!docs/**'
      - '!*.md'
      - '!mkdocs.yml'
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  FORCE_COLOR: 1

jobs:
  lints:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
    - uses: actions/checkout@v4
    - name: Install Uv
      uses: astral-sh/setup-uv@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Lint check
      run: ./nox -t check

  tests-linux:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    name: tests/${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Uv
      uses: astral-sh/setup-uv@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Install Rye
      run: |
        curl -sSf https://rye.astral.sh/get | RYE_TOOLCHAIN_VERSION=$(cat .python-version) RYE_INSTALL_OPTION="--yes" bash
        echo "$HOME/.rye/shims" >> $GITHUB_PATH
    - name: Install Hatch
      run: |
        uv tool install hatch
    - name: Tests
      run: |
        ./nox -t ci-linux

  tests-windows:
    runs-on: windows-latest
    name: tests-windows
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@v4
    - name: Install Uv
      uses: astral-sh/setup-uv@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Install Rye
      uses: eifinger/setup-rye@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Install Hatch
      env:
        UV_LINK_MODE: symlink
      run: |
        uv tool install hatch
    - name: Tests
      shell: bash
      env:
        UV_LINK_MODE: symlink
      run: |
          ./nox -t ci-windows
