name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  FORCE_COLOR: 1

jobs:
  tests-linux:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    - name: Install Uv
      uses: astral-sh/setup-uv@v3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Install Rye
      run: |
        curl -sSf https://rye.astral.sh/get | RYE_TOOLCHAIN_VERSION=$(cat .python-version) RYE_INSTALL_OPTION="--yes" bash
        echo "$HOME/.rye/shims" >> $GITHUB_PATH
    - name: Install Hatch
      run: |
        uv tool install hatch
    - name: Tests
      run: |
        ./nox

  tests-windows:
    runs-on: windows-latest
    name: tests-windows
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    - name: Install Uv
      uses: astral-sh/setup-uv@v3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Install Rye
      uses: eifinger/setup-rye@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Install Hatch
      run: |
        uv tool install hatch
    - name: Tests
      shell: bash
      run: |
          ./nox -s tests
          ./nox -s jupyter -k py312
