name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  tests-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Rye
      run: |
        curl -sSf https://rye.astral.sh/get | RYE_TOOLCHAIN_VERSION=$(cat .python-version) RYE_INSTALL_OPTION="--yes" bash
        echo "$HOME/.rye/shims" >> $GITHUB_PATH
    - name: Install Uv
      run: |
        rye tools install -f uv
    - name: Tests
      run: |
        make test-all

  tests-windows:
    runs-on: windows-latest
    name: tests-windows
    steps:
    - uses: actions/checkout@v4
    - name: Install Rye
      uses: eifinger/setup-rye@v4
      with:
        version: 'latest'
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Install Uv
      shell: bash
      run: |
        rye tools install -f uv
    - name: Tests
      run: |
        make test-all ARGS='"-ktests"'
        make test-all ARGS='"-sserver_client(py312)"'
