name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  tests-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Rye
      run: |
        curl -sSf https://rye.astral.sh/get | RYE_TOOLCHAIN_VERSION=$(cat .python-version) RYE_INSTALL_OPTION="--yes" bash
        echo "$HOME/.rye/shims" >> $GITHUB_PATH
    - name: Rye Sync
      run: |
        rye config --set-bool behavior.use-uv=true
        rye sync
    - name: Tests
      run: |
        rye test -v
    - name: Execute notebook
      run: |
        ./tests/server-client/setup_run.sh

  tests-windows:
    runs-on: windows-latest
    name: tests-windows
    steps:
      - uses: actions/checkout@v4
      - name: Install Rye
        shell: bash
        run: |
          C:/msys64/usr/bin/wget.exe -q 'https://github.com/astral-sh/rye/releases/latest/download/rye-x86_64-windows.exe' -O rye-x86_64-windows.exe
          ./rye-x86_64-windows.exe self install --toolchain-version $(cat .python-version) --modify-path -y
          echo "$HOME\\.rye\\shims" >> $GITHUB_PATH
      - name: Rye Sync
        shell: bash
        run: |
          rye config --set-bool behavior.use-uv=true
          rye sync
      - name: Tests
        shell: bash
        run: |
          rye test -v
      - name: Execute notebook
        shell: bash
        run: |
          ./tests/server-client/setup_run.sh
