name: Publish docs via GitHub Pages

on:
  push:
    paths:
      - 'docs/**'
      - 'tools/mkdocs-tool/**'
      - '*.md'
      - 'mkdocs.yml'
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    if: github.repository == 'bluss/pyproject-local-kernel'
    name: Deploy docs
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Install Uv
      uses: astral-sh/setup-uv@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Deploy docs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        uv run --project tools/mkdocs-tool mkdocs gh-deploy --force -v
