name: Publish docs via GitHub Pages

on:
  push:
    paths:
      - 'docs/**'
      - 'tools/mkdocs-tool/**'
      - '*.md'
      - 'mkdocs.yml'
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    if: github.repository == 'bluss/pyproject-local-kernel'
    name: Deploy docs
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Install Uv
      run: curl -LsSf https://astral.sh/uv/install.sh | sh
    - name: Prepare docs
      run: |
        cd tools/mkdocs-tool/
        uv export --frozen --no-hashes > requirements.txt
    - name: Deploy docs
      uses: mhausenblas/mkdocs-deploy-gh-pages@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CONFIG_FILE: mkdocs.yml
        REQUIREMENTS: tools/mkdocs-tool/requirements.txt
